apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-deployment
  labels:
    app: main-app
spec:
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
      - name: main-app-container
        image: 802103862232.dkr.ecr.ap-south-1.amazonaws.com/main_backend:latest
        command:
        args:
          - sh
          - -c
          - python
          - main.py
        ports:
        - containerPort: 8100	
      imagePullSecrets:
      - name: ap-south-1-ecr-registry
---
apiVersion: v1
kind: Service
metadata:
  name: main-app-service
spec:
  type: NodePort
  selector:
    app: main-app
  ports:
  - protocol: TCP
    port: 8100
    targetPort: 8100
    nodePort: 31100
